version: "3"

services:
  frontend:
    command: ["npm", "start"]
    # networks:
    #   - app-network
    ports:
      - 3000:3000

  backend:
    container_name: backend
    # networks:
    #   - app-network
    #   - priv-network
    entrypoint:
      [
        "uvicorn",
        "app.main:app",
        "--proxy-headers",
        "--reload",
        "--host",
        "0.0.0.0",
      ]
    ports:
      - 8000:8000

  # proxy:
  #   image: nginx:stable-alpine
  #   networks:
  #     - app-network
  #   ports:
  #     - 80:80
# networks:
#   app-network:
#     driver: bridge
#   priv-network:
#     driver: bridge
