version: "3"

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]
    ports:
      - 3000:3000

  backend:
    build:
      context: ./backend
    environment:
      SECRET_KEY: "7880a54f2e77f3d7cac9c6d5387e0821b2a4b8a1c6429adaa1d534ad6f6a7120"
    volumes:
      - ./backend:/pumps
    restart: unless-stopped
