version: "3"

services:
  frontend:
    build:
      context: ./frontend
      args:
        api_url: http://localhost:8000
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]
    ports:
      - 3000:3000

  backend:
    build:
      context: ./backend
    environment:
      SECRET_KEY: "7880a54f2e77f3d7cac9c6d5387e0821b2a4b8a1c6429adaa1d534ad6f6a7120"
      DATABASE_URI: "postgresql://pumps:secret@db/pumps"
    volumes:
      - ./backend:/pumps
    restart: unless-stopped

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    environment:
      POSTGRES_USER: pumps
      POSTGRES_PASSWORD: secret
