version: "3"

services:
  frontend:
    command: ["npm", "start"]
    ports:
      - 3000:3000

  backend:
    container_name: backend
    entrypoint: ["./start"]
    ports:
      - 8000:8000
  db:
    image: postgres
    environment:
      POSTGRES_DB: pumps
