version: "3"

services:
  frontend:
    build:
      context: ./frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
      - ./frontend/package-lock.json:/app/package-lock.json
    command: ["npm", "start"]
    ports:
      - 3000:3000
      - 35729:35729

  backend:
    build:
      context: ./backend
    environment:
      MONGODB_URI: "mongodb://root:example@mongo:27017/"
      # DO NOT USE THIS IN ANYWHERE OTHER THAN A TESTING OR DEVELOPMENT ENVIRONMENT
      SECRET_KEY: "7880a54f2e77f3d7cac9c6d5387e0821b2a4b8a1c6429adaa1d534ad6f6a7120"
    volumes:
      - ./backend:/pumps
    restart: unless-stopped

  proxy:
    image: nginx:stable-alpine
    networks:
      - app-network
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
