version: "3"

services:
  frontend:
    command: ["npm", "start"]
    ports:
      - 3000:3000

  backend:
    container_name: backend
    entrypoint:
      [
        "uvicorn",
        "app.main:app",
        "--proxy-headers",
        "--reload",
        "--host",
        "0.0.0.0",
      ]
    ports:
      - 8000:8000
