version: "3"

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]
    ports:
      - 3000:3000

  backend:
    build:
      context: ./backend
    environment:
      MONGODB_URI: "mongodb://root:example@mongo:27017/"
      # DO NOT USE THIS IN ANYWHERE OTHER THAN A TESTING OR DEVELOPMENT ENVIRONMENT
      SECRET_KEY: "7880a54f2e77f3d7cac9c6d5387e0821b2a4b8a1c6429adaa1d534ad6f6a7120"
    volumes:
      - ./backend:/pumps
    restart: unless-stopped

  # proxy:
  #   image: nginx:stable-alpine
  #   networks:
  #     - app-network
  #   volumes:
  #     - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   ports:
  #     - 80:80
