version: "3"

services:
  frontend:
    build:
      context: ./frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
      - ./frontend/package-lock.json:/app/package-lock.json
    entrypoint: ["npm", "start"]
    networks:
      - app-network
    ports:
      - 3000:3000
      - 35729:35729

  backend:
    build:
      context: ./backend
    networks:
      - app-network
    entrypoint:
      [
        "uvicorn",
        "main:app",
        "--proxy-headers",
        "--reload",
        "--host",
        "0.0.0.0",
        "--root-path",
        "/api/v1",
      ]
    ports:
      - 8000:8000

  proxy:
    image: nginx:stable-alpine
    # build:
    #   context: ./proxy
    networks:
      - app-network
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80

networks:
  app-network:
    driver: bridge
