version: "3"

services:
  frontend:
    build:
      context: ./frontend
      args:
        env: production
        api_url: http://backend:8000
    command: ["npm", "run", "start"]
    ports:
      - 3000:3000
      - 35729:35729

  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - db
    environment:
      # DO NOT USE THIS IN ANYWHERE OTHER THAN A TESTING OR DEVELOPMENT ENVIRONMENT
      SECRET_KEY: "7880a54f2e77f3d7cac9c6d5387e0821b2a4b8a1c6429adaa1d534ad6f6a7120"
      DATABASE_URI: "postgresql://pumps:secret@db/pumps"
    entrypoint: ["./start", "smoke"]

  e2e:
    image: cypress
    build: ./e2e
    container_name: cypress
    depends_on:
      - frontend
      - backend
    environment:
      CYPRESS_baseUrl: "http://frontend:3000"
      DATABASE_URI: "postgresql://pumps:secret@db/pumps"
    command: npx cypress run --config "video=false" --config "screenshotOnRunRailure=false"
    volumes:
      - ./e2e/cypress:/app/cypress
      - ./e2e/cypress.json:/app/cypress.json

  db:
    image: postgres
    environment:
      POSTGRES_USER: pumps
      POSTGRES_PASSWORD: secret
