version: "3"

services:
  frontend:
    build:
      context: ./frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
      - ./frontend/package-lock.json:/app/package-lock.json
    command: ["npm", "start"]
    networks:
      - app-network
    ports:
      - 3000:3000
      - 35729:35729

  backend:
    build:
      context: ./backend
    networks:
      - app-network
      - priv-network
    environment:
      MONGODB_URI: "mongodb://root:example@mongo:27017/"
    volumes:
      - ./backend/main.py:/app/main.py
      - ./backend/requirements.txt:/app/requirements.txt
    restart: always
    entrypoint:
      [
        "uvicorn",
        "main:app",
        "--proxy-headers",
        "--reload",
        "--host",
        "0.0.0.0",
        "--root-path",
        "/api/v1",
      ]
    ports:
      - 8000:8000

  mongo:
    image: mongo
    restart: always
    networks:
      - priv-network
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - priv-network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  proxy:
    image: nginx:stable-alpine
    # build:
    #   context: ./proxy
    networks:
      - app-network
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80

networks:
  app-network:
    driver: bridge
  priv-network:
    driver: bridge
