"""add exercises

Revision ID: 1168360fbc87
Revises: 31741b436e66
Create Date: 2022-01-01 13:26:20.154400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1168360fbc87'
down_revision = '31741b436e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    op.create_table('plan_workout',
    sa.Column('plans_id', sa.Integer(), nullable=True),
    sa.Column('workouts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plans_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['workouts_id'], ['workouts.id'], )
    )
    op.create_table('workout_exercise',
    sa.Column('workouts_id', sa.Integer(), nullable=True),
    sa.Column('exercises_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercises_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workouts_id'], ['workouts.id'], )
    )
    op.drop_table('workout_plan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_plan',
    sa.Column('plans_id', sa.INTEGER(), nullable=True),
    sa.Column('workouts_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['plans_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['workouts_id'], ['workouts.id'], )
    )
    op.drop_table('workout_exercise')
    op.drop_table('plan_workout')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
