"""microcycle workouts

Revision ID: 63b3cb22423c
Revises: f11d8dd77602
Create Date: 2022-02-13 15:59:00.516484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b3cb22423c'
down_revision = 'f11d8dd77602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('microcycle_workout',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('microcycle_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('plan_id', 'workout_id')
    )
    op.drop_table('plan_workout')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length_in_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('length_in_days')

    op.create_table('plan_workout',
    sa.Column('plans_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('workouts_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plans_id'], ['plans.id'], name='plan_workout_plans_id_fkey'),
    sa.ForeignKeyConstraint(['workouts_id'], ['workouts.id'], name='plan_workout_workouts_id_fkey')
    )
    op.drop_table('microcycle_workout')
    # ### end Alembic commands ###
