"""add avatar_owner_description to exercise

Revision ID: f11d8dd77602
Revises: 1168360fbc87
Create Date: 2022-01-01 15:26:12.911452

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f11d8dd77602'
down_revision = '1168360fbc87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('description', sa.String(), nullable=True))
    op.add_column('exercises', sa.Column('avatar_id', sa.Integer(), nullable=True))
    op.add_column('exercises', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_exercises_avatar_id'), 'exercises', ['avatar_id'], unique=False)
    op.create_foreign_key(None, 'exercises', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_index(op.f('ix_exercises_avatar_id'), table_name='exercises')
    op.drop_column('exercises', 'owner_id')
    op.drop_column('exercises', 'avatar_id')
    op.drop_column('exercises', 'description')
    # ### end Alembic commands ###
